language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - composer selfupdate --no-interaction
  - composer install --no-interaction

script: phpunit --configuration phpunit.xml --coverage-text
